- .prettierrc.yml
---
I edited the Prettier settings to reflect our Team Norms
> Api routes

- package-lock.json
- package.json
- server/db/models/index.js
- server/db/models/wig.js
- server/db/models/wig.spec.js
---
Wrote Wig model, test for Wig model, and imported wig model into models/index.js
> Models wigs #7

- client/store/index.js
- client/store/user.js
- client/store/wigs.js
- client/store/wigs.spec.js
---
Updated redux for all wigs & completed two test specs that are passing
> Wigs redux file with two test specs

- client/store/index.js
- client/store/user.js
- client/store/wigs.js
> feature: getAllWigs redux fixed first few bugs

- client/store/reducers/cart.js
- client/store/reducers/cart.spec.js
- client/store/reducers/index.js
---
Cart for redux store, tests passing, connected to combine reducers.
> Cart redux store

- server/api/index.js
- server/api/orders.js
- server/api/orders.spec.js
- server/db/models/orders.js
---
Feature: Created Orders POST route to create a new order
> Feature: POST order API route

- client/components/checkoutForm.js
- client/store/reducers/cart.js
- client/store/reducers/cart.spec.js
- client/store/reducers/index.js
- client/store/reducers/order.js
- client/store/reducers/order.spec.js
- client/store/reducers/wigs.js
> Checkout form

- client/components/checkoutForm.js
- client/components/tempForm.js
- client/components/viewCart.js
- client/components/wig-card.js
- client/routes.js
- public/style.css
---
updated viewCart component to link to checkoutForm component
> updated viewCart component to link to checkoutForm component

- client/components/viewCart.js
- client/store/reducers/cart.js
- server/api/lineItems.js
- server/api/wigs.js
- server/api/wigs.spec.js
- server/db/models/wig.js
> Feature: Can add multiple of one wig to cart and see the cart

- script/seed.js
> Fix: Seed file provides price in pennies

- script/seed.js
---
Seed file now seeds price with integer.
> Fix: seed file price in pennies, no decimals

- client/components/checkoutForm.js
- client/components/viewCart.js
- client/components/wig-card.js
- client/store/reducers/cart.js
- client/store/reducers/index.js
- client/store/reducers/total.js
---
created total reducer linked to addToCart onClick function in order to update total in store
> created total reducer to store total in store

- client/components/checkoutForm.js
- client/components/viewCart.js
- client/components/wig-card.js
- client/store/reducers/total.js
- server/api/wigs.js
- server/db/models/wig.js
---
Updated wigModel to display pennies; viewAll, viewCart, and checkout displays price in dollar amounts; simple order summary now appears on checkout page.
> Total in store

- script/seed.js
- server/api/index.js
- server/db/models/user.js
- server/security.js
---
Denies access to API routes for nonAdmin users on localhost!
> Feature: deny API access to nonAdmin

- client/components/checkoutForm.js
- client/store/reducers/cart.js
- client/store/reducers/order.js
- server/api/orders.js
- server/db/models/index.js
- server/db/models/orders.js
---
Edited Order model to include the shipping address name, updated associations to make an order belong to one user, updated CheckoutForm component to include a user on the order, and updated order POST route to set the userId.
> Fix: Updated order model, associations and api route to post an order

- client/components/viewCart.js
- client/store/reducers/cart.js
- client/store/reducers/index.js
- client/store/reducers/total.js
---
Remove items from cart & update total in store
> Remove item from cart 94

- client/components/checkoutForm.js
- client/store/reducers/cart.js
- client/store/reducers/total.js
- client/store/reducers/wigs.js
---
Feature: Clicking Place Order on checkout form sets the total back to 0, dispatches placeNewOrder to update the quantity of wigs in the Redux store
> Update redux wigs

- client/components/checkoutForm.js
- client/components/order-completed.js
- client/routes.js
---
Feature: Show Thank you message visitor places their order
> Show message purchase

- client/components/viewCart.js
- client/store/reducers/cart.js
- client/store/reducers/total.js
---
Hopefully fixed removeItems from Cart functionality!
> update and fix removeItem errors

- server/api/index.js
- server/api/users.js
- server/security.js
---
Added admin and user checks to user API routes
> Fix: increased API security

- server/api/index.js
- server/api/orders.js
- server/security.js
---
Update security on backend
> Fix security

- client/components/checkoutForm.js
- client/components/viewCart.js
- client/components/wig-card.js
---
Fixed components to display trailing zeros
> Decimals on price #117

- client/components/checkoutForm.js
- client/components/viewCart.js
- client/store/reducers/cart.js
- client/store/reducers/index.js
- client/store/reducers/total.js
- server/api/orders.js
---
Fix: Refactored placeOrder thunk creator into two thunks
> Fix: refactored placeOrder thunk creator into two thunks

- server/db/models/wig.js
---
Updated wig model to have specific choices for properties.
> Fix: refactor wig model to include wig styles

- client/components/checkoutForm.js
- client/components/viewCart.js
- public/style.css
> View cart css

- client/components/checkoutForm.js
- public/style.css
> Fix: place order button

- client/components/navbar.js
- public/index.html
- public/style.css
- public/style2.css
---
Makes nav bar more beautiful.
> Nav bar css
